baseURL: "https://thisplatypus.github.io/" 
title: Chiara Camerota
theme: PaperMod

enableInlineShortcodes: true
enableRobotsTXT: true

taxonomies:
    tag: tags

menu:
    main:
        - name: Research
          url: papers/
          weight: 2
        - name: Work in Progress
          url: wp/
          weight: 3
        - name: Home
          url: /
          weight: 1
        - name: Education
          url: data/
          weight: 4 


params:
    description: “I am a Ph.D. candidate in Information Engineering at the University of Florence, Italy.”
    author: Chiara 
    # googleAnalyticsID: "G-XXXXX"
    DateFormat: "January 2025"
    defaultTheme: light
    hideFooter: false
    disableThemeToggle: true
    ShowShareButtons: false
    ShowReadingTime: false
    disableSpecial1stPost: true
    disableAnchoredHeadings: true
    ShowPostNavLinks: false
    ShowBreadCrumbs: false
    ShowCodeCopyButtons: true
    ShowAllPagesInArchive: false
    MainSections: ["courses","papers","data"]
    ShowToc: false
    disableScrollToTop: true
    TocOpen: true
    ShowWordCount: false
    UseHugoToc: true
    comments: false
    math: true
    profileMode:
          enabled: true
          title: Chiara Camerota, Ph.D.
          subtitle: I am a Ph.D. candidate in Information Engineering at the University of Florence, Italy. My research focuses on applying machine learning to network systems and computer vision. I was a doctoral student of Professor Tommaso Pecorella in Florence and am now beginning a post-doctoral position at Saint Louis University in St. Louis, MO, working with Professor Flavio Esposito. 
          imageUrl: "picture.jpeg"
          imageWidth: 160
          imageHeight: 160
          buttons:
            - name: Research
              url: papers/
            - name: Work in Progress
              url: wp/
            - name: Education
              url: data/

            
            

    socialIcons:
        - name: CV
          url: cv.pdf
        - name: Email
          url: mailto:camerota.chiara.c@gmail.com
        - name: Google Scholar
          url: https://scholar.google.com/citations?user=qoGLRa0AAAAJ&hl=it
        - name: GitHub
          url: https://github.com/ThisPlatypus
        - name: Linkedin
          url: https://www.linkedin.com/in/chiara-camerota/

    assets:
        disableScrollBarStyle: true
    cover:
        hiddenInList: false
        hiddenInSingle: true
    label:
      text: "Chiara Camerota"
      icon: favicon.ico
      iconHeight: 18

markup:
    goldmark:
        renderer:
            unsafe: true
    highlight:
        guessSyntax: true
        style: autumn 
    tableOfContents:
        endLevel: 2
        ordered: false
        startLevel: 2